# Basic
title: Louis_Zhu
subtitle: 过去.现在.未来
welcome_message: and u dont wanna fxxk with a chigga like me hhh..
description: 嗨，我是诸峻豪(@ultraviolent)，一名来自中国的  java/iOS  开发者。现居杭州，就职于 环球黑卡。正在修行，探求创意之源。
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://ultraviolent.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: ''}
    - {title: 关于, description: 了解更多关于我, url: ''}
    - {title: 订阅, description: 邮件订阅本站, url: ''}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: ultraviolent
    # duoshuo:
# Social
social:
    weibo: -诸英俊
    github: ultraviolent
    mail: onev@onevcat.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: ultraviolent.github.io
